#!/usr/bin/env bash

shopt -s extglob

# ============================================================================================ #
#: Title           : setx                                                                      #
#: Sypnosis        : setx [OPTION] [FILE]                                                      #
#: Date Created    : Tue May 31 15:59:31 PHT 2016 / Tue May 31 07:59:31 UTC 2016               #
#: Last Edit       : Sat Jun 18 11:50:16 PHT 2016 / Sat Jun 18 03:50:16 UTC 2016               #
#: License         : GPLv3                                                                     #
#: Version         : 1.2.0                                                                     #
#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
#: Description     : Insert/Add `Debug code' on the second line/after the shebang.             #
#: Options         : [-i|--insert] [-d|--delete] [-h|?|--help]                                 #
#: Home Page       : NONE                                                                      #
#: ExtComm         : cat,ed,file                                                               #
# ============================================================================================ #

# ******************************************************************************************** #
#                                                                                              #
#   Warn and die functions, for exit messages and default status or an optional exit status.   #
#                                                                                              #
# ******************************************************************************************** #

warn() {
  printf '%s\n' "${BASH_SOURCE##*/}: $*" 
}

die() {
  local st=$? 
  case $2 in  
    *[^0-9]*|'') :;; 
    *) st=$2;; 
  esac

  case $st in 
    0) warn "$1" ;;  
    *) warn "$1" >&2;; 
  esac

  exit "$st"  
} 

# ******************************************************************************************** #
#                                                                                              #
#          Check for the required app/executable is with in your PATH, exit otherwise.         #
#                                                                                              #
# ******************************************************************************************** #

Missing=()
ExtComm=(ed file)
MissingMessage="is either not installed or it is not in your PATH!"
ExitMessage="Please install the following: "

for apps in "${ExtComm[@]}"; do
  if ! type -P "$apps" >/dev/null; then
    printf '%s %s\n' "$apps" "$MissingMessage" >&2
    Missing+=("$apps")
  fi
done

(( ${#Missing[@]} )) && die "$ExitMessage[${Missing[*]}] exiting now!" 127

# ******************************************************************************************** #
#                                                                                              #
#                                     The help/usage menu.                                     #
#                                                                                              #
# ******************************************************************************************** #

ShowHelp() {
   cat <<EOF

Usage: ${BASH_SOURCE##*/} OPTION FILE

Options:
  -i, --insert   Insert \`set -x' and \`PS4' debug code below the shebang.
  -d, --delete   Remove \`set -x' and \`PS4' debug code below the shebang.
  -h, --help     Show this help.
  -a, --about    A brief info.

EOF
}

# ******************************************************************************************** #
#                                                                                              #
#                        Function to print some info about the script.                         #
#                                                                                              #
# ******************************************************************************************** #

About() {
   cat <<EOF

                           setx

Copyright  (c)  2016 Jason V. Ferrer  '<jetchisel@opensuse.org>'

A bash shell  script  that  inserts \`set -x' and a \`PS4' debug 
code right after the shebang. Shell script is a bit more verbose 
when  the code is  added in  the script in question. This script 
relies  heavily on GNU ed(1)  for editing  the shell  script and 
file(1) for testing the file type of the script in question.

This  program is  free software;  you can redistribute it and/or
modify  it  under  the terms  of the  GNU General Public License
version 3 as published by the Free Software Foundation.

This program is  distributed in the hope that it will be useful,
but WITHOUT  ANY WARRANTY; without even the  implied warranty of
MERCHANTABILITY  or  FITNESS  FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

EOF
}

# ******************************************************************************************** #
#                                                                                              #
#                              Function to insert the debug code.                              #
#                                                                                              #
# ******************************************************************************************** #

FiLe=$2 

InsertDebug() {
  local DebugCode LineNumber
  LineNumber=$1 
  DebugCode=('set -x' PS4=''\''+($?) $BASH_SOURCE:$FUNCNAME:$LINENO:'''\') 
  printf '%s\n' "$LineNumber" "${DebugCode[@]}" . w q | ed -s "$FiLe"
}

# ******************************************************************************************** #
#                                                                                              #
#      Function to do some various if not extensive testing about the file type of `$2'.       #
#                                                                                              #
# ******************************************************************************************** #

TestFile() {
  File=""\`$FiLe"""'" 
  FileType=$(file --mime-type -b -- "$FiLe") 
  
  [[ $FileType = "cannot open $File (No such file or directory)" ]] && die "$FileType" 1
  [[ $FileType = "cannot open $File (Permission denied)" ]] && die "$FileType" 1
  [[ $FileType = "inode/x-empty" ]] && die "$File is an empty file!" 1
  [[ $FileType = text* ]] || die "File type of $File is $FileType" 1
  
  [[ -w $FiLe ]] || die "cannot write to $File (Permission denied)" 1
  [[ -r $FiLe ]] || die "cannot read $File (Permission denied)" 1
  TotalLines=$(ed -s "$FiLe" <<< $'$=') 
  
  { read -r first; read -r second ; } < "$FiLe"
  
  
  NotShell() {
    die "$File does not appear to be a shell script: [$first]" 1
  }

  [[ ${first:0:2} = '#!' ]] || NotShell 
  
  if [[ ${first#*+( )} = -* ]]; then 
    [[ ${first%+( )*} != *@(bash|ash|sh|ksh|zsh) ]] && NotShell 
  fi
  
  if [[ ${first#*+( )} != -* ]]; then 
    [[ ${first#*+( )} = *@(bash|ash|sh|ksh|zsh) ]] || NotShell 
  fi
}

# ******************************************************************************************** #
#                                                                                              #
#           Loop through the command line input (arguments/options) and process it.            #
#                                                                                              #
# ******************************************************************************************** #

while (( $# )); do
  case $1 in
    -a|--about)
           (( $# > 1 )) && die "Invalid option!, try: ""\`"--help"""'" 1
           About
           exit
           ;;
    -h|-\?|--help)
           (( $# > 1 )) && die "Invalid option!, try: ""\`"--help"""'" 1
           ShowHelp
           exit
           ;;
    -i|--insert)  
        [[ ! "$FiLe" ]] && die "No script is given!, try: ""\`"--help"""'" 1
        TestFile 
        
        [[ $second = 'set -x' ]] && die "$File is already in debug mode!" 1 
        
        if (( TotalLines == 1 )); then 
          InsertDebug '$a' && die "Successfully added debug after the shebang of $File" 0
        else 
          InsertDebug '2i' && die "Successfully added debug after the shebang of $File" 0 
        fi
        ;;
    -d|--delete) 
        [[ ! "$FiLe" ]] && die "No script is given!, try: ""\`"--help"""'" 1
        TestFile 
        if [[ $second = 'set -x' ]]; then 
          if printf '%s\n' '/^set -x/;+1d' w q | ed -s "$FiLe"; then 
            die "Removed 'debug' after the shebang of $File" 0
          fi
        else 
          die "$File is not in debug mode, nothing to remove!" 1
        fi
        ;;
       *) ShowHelp >&2
          exit 1
        ;; 
  esac
done

# ******************************************************************************************** #
#                                                                                              #
#                     Show the help/usage if no option/arguments is given.                     #
#                                                                                              #
# ******************************************************************************************** #

ShowHelp >&2
exit 1

# ============================================================================================ #
#                                                                                              #
#                                   >>> END OF SCRIPT <<<                                      #
#                                                                                              #
# ============================================================================================ #
