#!/usr/bin/env bash

shopt -s extglob

# ============================================================================================ #
#: Title           : setx                                                                      #
#: Sypnosis        : setx [OPTION] [FILE]                                                      #
#: Date Created    : Tue May 31 15:59:31 PHT 2016 / Tue May 31 07:59:31 UTC 2016               #
#: Last Edit       : Thu Jun 16 19:43:00 PHT 2016 / Thu Jun 16 11:43:00 UTC 2016               #
#: License         : GPLv3                                                                     #
#: Version         : 1.0.6                                                                     #
#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
#: Description     : Insert/Add `Debug code' on the second line/after the shebang.             #
#: Options         : [-i|--insert] [-d|--delete] [-h|?|--help]                                 #
#: Home Page       : NONE                                                                      #
#: ExtComm         : ed,file                                                                   #
# ============================================================================================ #

# ******************************************************************************************** #
#                                                                                              #
#   Warn and die functions, for exit messages and default status or an optional exit status.   #
#                                                                                              #
# ******************************************************************************************** #

warn() {
  printf '%s\n' "${BASH_SOURCE##*/}: $*" >&2
}

die() {
  local st=0
  case $2 in
    *[^0-9]*|'') :;;
    *) st=$2;;
  esac
  warn "$1"
  exit "$st"
}

# ******************************************************************************************** #
#                                                                                              #
#          Check for the required app/executable is with in your PATH, exit otherwise.         #
#                                                                                              #
# ******************************************************************************************** #

Missing=()
ExtComm=(ed file)
MissingMessage="is either not installed or it is not in your PATH!"
ExitMessage="Please install the following: "

for apps in "${ExtComm[@]}"; do
  if ! type -P "$apps" >/dev/null; then
    printf '%s %s\n' "$apps" "$MissingMessage" >&2
    Missing+=("$apps")
  fi
done

(( ${#Missing[@]} )) && die "$ExitMessage[${Missing[*]}] exiting now!" 127

# ******************************************************************************************** #
#                                                                                              #
#                                     The help/usage menu.                                     #
#                                                                                              #
# ******************************************************************************************** #

ShowHelp() {
   cat <<EOF

Usage: ${BASH_SOURCE##*/} OPTION FILE

Options:
  -i, --insert   Insert 'set -x' at the second line after the shebang.
  -d, --delete   Removed 'set -x' at the second line after the shebang.
  -h, --help     Show this help.
  -a, --about    A brief info.
  -l, --license  Show license.

EOF
return
}

# ******************************************************************************************** #
#                                                                                              #
#                              Function to insert the debug code.                              #
#                                                                                              #
# ******************************************************************************************** #

FiLe=$2 

InsertDebug() {
  local DebugCode LineNumber
  LineNumber=$1
  DebugCode=('set -x' PS4=''\''+($?) $BASH_SOURCE:$FUNCNAME:$LINENO:'''\')

  printf '%s\n' "$LineNumber" "${DebugCode[@]}" . w q | ed -s "$FiLe"
}

# ******************************************************************************************** #
#                                                                                              #
#               Continue looping through the arguments/options until none left.                #
#                                                                                              #
# ******************************************************************************************** #

while (($#)); do 
  if (( $# < 2 )); then 
    ShowHelp 
    exit 1 
  fi

  File=""\`$2"""'" 
  FileType=$(file --mime-type -b -- "$2") 
  
  [[ $FileType = "cannot open $File (No such file or directory)" ]] && die "$FileType" 1
  [[ $FileType = "cannot open $File (Permission denied)" ]] && die "$FileType" 1
  [[ $FileType = "inode/x-empty" ]] && die "$File is an empty file!" 1
  [[ $FileType = text* ]] || die "File type of $File is $FileType" 1
  
  [[ -w $2 ]] || die "cannot write to $File (Permission denied)" 1
  [[ -r $2 ]] || die "cannot read $File (Permission denied)" 1
  TotalLines=$(ed -s "$2" <<< $'$=') 
  
  { read -r first; read -r second ; } < "$2"
  
  
  NotShell() { 
    die "$File does not appear to be a shell script: [$first]" 1
  }
  
  [[ ${first:0:2} = '#!' ]] || NotShell 
  
  if [[ ${first#*+( )} = -* ]]; then 
    [[ ${first%+( )*} != *@(bash|ash|sh|ksh|zsh) ]] && NotShell 
  fi  
  
  if [[ ${first#*+( )} != -* ]]; then 
    [[ ${first#*+( )} = *@(bash|ash|sh|ksh|zsh) ]] || NotShell 
  fi
  
  case $1 in
    -i|--insert) 
        
        [[ $second = 'set -x' ]] && die "$File is already in debug mode!" 1 
        
        if (( TotalLines == 1 )); then 
          InsertDebug '$a' && die "Successfully added debug after the shebang of $File" 0
        else 
          InsertDebug '2i' && die "Successfully added debug after the shebang of $File" 0 
        fi
        ;;
    -d|--delete) 
        if [[ $second = 'set -x' ]]; then 
          if printf '%s\n' '/^set -x/;+1d' w q | ed -s "$2"; then 
            die "Removed 'debug' after the shebang of $File" 0
          fi
        else 
          die "$File is not in debug mode, nothing to remove!" 1
        fi
        ;;
    -h|\?|--help) ShowHelp
        exit 0
        ;;
     *) ShowHelp
        exit 1 
        ;;
  esac
done

# ******************************************************************************************** #
#                                                                                              #
#                   Show usage/help menu if no option or argument is given.                    #
#                                                                                              #
# ******************************************************************************************** #

ShowHelp

# ******************************************************************************************** #
#                                                                                              #
#                                    Set the exit staus.                                       #
#                                                                                              #
# ******************************************************************************************** #

exit $? 

# ============================================================================================ #
#                                                                                              #
#                                   >>> END OF SCRIPT <<<                                      #
#                                                                                              #
# ============================================================================================ #
